# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: true
cache: packages

r_github_packages:
  - jimhester/covr

r_check_args: "--no-build-vignettes"

script:
  - R CMD build .
  - travis_wait 30 R CMD check *.tar.gz

after_success:
  - travis_wait 30 Rscript coverage.R
